// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJOziIgp85S_O-4a8Tm3URf1pcfB-A2n0',
    appId: '1:726424196389:web:0433c446cd8b75712536cc',
    messagingSenderId: '726424196389',
    projectId: 'trashtag-app--signin',
    authDomain: 'trashtag-app--signin.firebaseapp.com',
    storageBucket: 'trashtag-app--signin.appspot.com',
    measurementId: 'G-KW01Q0S3P5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDENoo4_rJ_XvTBBAE1pAYlJ-5uVz1eTmw',
    appId: '1:726424196389:android:140ec26efed293262536cc',
    messagingSenderId: '726424196389',
    projectId: 'trashtag-app--signin',
    storageBucket: 'trashtag-app--signin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjTDfpCRY6uKMGNVw5To8YJuIedluNkSA',
    appId: '1:726424196389:ios:b006e0435795402d2536cc',
    messagingSenderId: '726424196389',
    projectId: 'trashtag-app--signin',
    storageBucket: 'trashtag-app--signin.appspot.com',
    androidClientId: '726424196389-7ig1hivdkpv0pmd81fntfqrgshbnfmql.apps.googleusercontent.com',
    iosClientId: '726424196389-hft5ng1plq1a3qjnk8b9e1lefitj44uh.apps.googleusercontent.com',
    iosBundleId: 'io.trashtag.trashtagCity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjTDfpCRY6uKMGNVw5To8YJuIedluNkSA',
    appId: '1:726424196389:ios:b006e0435795402d2536cc',
    messagingSenderId: '726424196389',
    projectId: 'trashtag-app--signin',
    storageBucket: 'trashtag-app--signin.appspot.com',
    androidClientId: '726424196389-7ig1hivdkpv0pmd81fntfqrgshbnfmql.apps.googleusercontent.com',
    iosClientId: '726424196389-hft5ng1plq1a3qjnk8b9e1lefitj44uh.apps.googleusercontent.com',
    iosBundleId: 'io.trashtag.trashtagCity',
  );
}
